cpanel/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.signin),

    path('postsignin/', views.postsignin),

    path('orderform/', include('orderform.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orderform/urls.py
from django.conf.urls import url

from . import views
from .views import *


app_name = "orderform"


urlpatterns = [
    # # /orderform/
    # url(r'^$', views.orderform, name='index'),

    # /orderform/cakemonster
    url(r'^cakemonster/$', OrderCreate.as_view(), name='cakemonster'),

    # /orderform/listorders
    url(r'^listorders/$', ListOrders.as_view(), name='listorders'),

    # /orderform/cakemonsterview
    url(r'^cakemonsterview/$', views.cakemonster, name='cakemonsterview'),

    # /orderform/2/update
    url(r'^(?P<pk>[0-9]+)/update/$', OrderUpdate.as_view(), name="updateorder"),

    # /orderform/2/statusupdate
    url(r'^(?P<pk>[0-9]+)/statusupdate/$', StatusUpdate.as_view(), name="statusupdate"),

]

orderform/models.py
from django.db import models
from django.shortcuts import render
# Create your models here.
from django.urls import reverse


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'documents/{0}/{1}_{2}/{3}'.format(instance.date, instance.fullname,instance.contactnumber, filename)

class Order(models.Model):
    STATUS_VALUES = (
        (-1, 'Rejected'),
        (0, 'Not-Accepted'),
        (1, 'Accepted'),
        (2, 'Ready-for-delivery'),
        (3, 'Completed'),
    )
    FLAVOR_VALUES = (
        (0, 'Chocolate Chip'),
        (1, 'Chocolate Fudge'),
        (2, 'Nutella'),
        (3, 'Cheese'),
        (4, 'Strawberry Cheese'),
    )
    fullname = models.CharField(max_length=300)
    contactnumber = models.CharField(max_length=300)
    date = models.DateField()
    time = models.TimeField()
    # flavor = models.CharField(max_length=300)
    flavor = models.IntegerField(default=0, choices=FLAVOR_VALUES)
    image1 = models.FileField(null=True,upload_to=user_directory_path)
    image2 = models.FileField(null=True,upload_to=user_directory_path)
    # image1 = models.FileField(null=True,upload_to='documents/%Y%m%d/')
    # image2 = models.FileField(null=True,upload_to='documents/%Y%m%d/')
    status = models.IntegerField(default=0, choices=STATUS_VALUES)

    def get_absolute_url(self):
        print ("get abosilte url\r\n\r\n")
        return "%s?posted=yes" % reverse('orderform:cakemonster')

cpanel/views.py
from django.shortcuts import render
import pyrebase


# Initialize Firebase
config = {
"apiKey": "AIzaSyDYxrIRcJBwuGYmcM_OuMDuqqHgEpKYxd0",
"authDomain": "asaleem-firebase.firebaseapp.com",
"databaseURL": "https://asaleem-firebase.firebaseio.com",
"projectId": "asaleem-firebase",
"storageBucket": "asaleem-firebase.appspot.com",
"messagingSenderId": "415533361545"
};

firebase = pyrebase.initialize_app(config)

auth = firebase.auth()

def signin(request):
    return render (request, "signin.html")

def postsignin(request):
    email = request.POST.get('email')
    password = request.POST.get('pass')

    try:
        user= auth.sign_in_with_email_and_password(email, password)
    except:
        message = "invalid credentials"
        return render(request, "signin.html", {"message":message})
    print (user)
    return render (request, "welcome.html", {"e":email})

orderform/views.py
from django.shortcuts import render
import pyrebase
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from .models import  Order
from django import forms
from django.views import generic
from django.contrib.admin import widgets
import datetime

# def orderform(request):
#     return render(request, 'orderform.html')

class OrderForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        self.fields['date'].label = "Delivery Date"
        self.fields['time'].label = "Delivery Time"
        self.fields['date'].widget.input_type = "date"
        self.fields['time'].widget.input_type = "time"
        self.fields['contactnumber'].widget.input_type = "text"
        # print (self.fields.values())
        # print (self.fields)
        for field in self.fields.values():
            # print (field.label)
            if field.label == 'Contactnumber':
                field.widget.attrs = {'class': 'form-control', 'placeholder': '0321-1234567', 'pattern' : '[0-9]{4}-[0-9]{7}'}
            elif field.label == 'Delivery Date':
                # field.widget.attrs = {'class': 'form-control', 'onchange': 'checkdate()'}
                field.widget.attrs = {'class': 'form-control'}
            else:
                field.widget.attrs = {'class': 'form-control'}

    class Meta:
        model = Order
        # fields = "__all__"
        fields = ['fullname','date','time', 'contactnumber', 'flavor', 'image1', 'image2']

class OrderCreate(CreateView):
    model = Order
    form_class = OrderForm

    # no need for this function but let it be
    def form_valid(self, form):
        obj = form.save(commit=False)
        return super(OrderCreate, self).form_valid(form)

class OrderUpdate(UpdateView):
    form_class = OrderForm
    model = Order

class StatusUpdate(UpdateView):
    model = Order
    fields = ['status']
    success_url = reverse_lazy('orderform:listorders')
    template_name = "orderform/statusupdate_form.html"


    def get_success_url(self):
        # can be used to presever query parameters
        print (len(self.request.GET))
        return self.success_url

class ListOrders(generic.ListView):
    template_name = "orderform/orders.html"
    context_object_name = 'all_orders'

    def get_queryset(self):
        start_date = self.request.GET.get('startdate')
        end_date = self.request.GET.get('enddate')
        # if self.request.user.is_authenticated():
        if (start_date != "" and start_date != None and end_date != None and end_date!=""):
            print ("\r\n\r\n\r\n\r\n\r\n")
            print (start_date)
            print (end_date)
            return Order.objects.filter(date__range=[start_date, end_date]).order_by('-date','time')

        #current date
        # (datetime.datetime.now().date())

        return Order.objects.all().order_by('-date','time')
        # else:
        #     return None


def cakemonster(request):
     return render(request, 'orderform/cakemonster.html')

orderform/templates/orderform/base.html
<html lang="en">
<head>
        <title>
            {% block title %}
                OrderForm
            {% endblock%}
        </title>
        {% load staticfiles %}

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
        <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css' />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

        {% block head %}
        {% endblock %}
</head>

<body>
{% block body %}
{% endblock%}
</body>
</html>

orderform/templates/orderform/listorders.html
{#{% extends 'orderform/base.html' %}#}
{% extends 'orderform/cakemonster.html' %}

{% block title%}
CakeMonster Order List
{% endblock%}

{% block head %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
<script>

$(document).ready( function () {
    $('.table').DataTable();
} );

$(document).on("click", ".xyz", function () {
     var myBookId = $(this).data('id');
        console.log("working?");
        console.log(myBookId);
        var url_mask = "{% url 'orderform:statusupdate' 12345 %}".replace(/12345/, myBookId);
 {#$(".modal-body #bookId").val( myBookId );#}
     // As pointed out in comments,
     // it is superfluous to have to manually call the modal.
        $.ajax({url: url_mask, success: function(result){
            console.log(result);
            $(".modal-body").html(result);

            $('#orderform').attr('action', url_mask);

        }});
      {#$('.modal-body .form-group #orderid').val(myBookId);#}
});

</script>
{% endblock %}

{% block body%}
<div class="container">
    <div class="row well">
        <!--<div class ="col-md-12">-->
            <div class ="col-md-3">
                <form action="{% url 'orderform:listorders'  %}" method="GET" >
                    <button type="submit" class="btn btn-default">Show All Orders</button>
                </form>
            </div>
            <div class ="col-md-9">
                <form class="form-inline" action="" method="GET" >
                    <div class="form-group">
                      <label for="date">Start Date:</label>
                      <input type="date" class="form-control" placeholder="Enter start date" name="startdate">
                    </div>
                    <div class="form-group">
                      <label for="date">End Date:</label>
                      <input type="date" class="form-control" placeholder="Enter end date" name="enddate">
                    </div>
                    <button type="submit" class="btn btn-default">Search</button>
                </form>
            </div>
        <!--</div>-->
    </div>
    <div class="row">
{#        <div class ="col-md-1">#}
{#        </div>#}
        <div class ="col-md-12 well" >
            <div class="table-responsive">
                <h3>Order List</h3>
                    {% if request.GET.startdate != "" and request.GET.startdate != None %}
                        <p>Start date: {{ request.GET.startdate }}</p>
                    {% endif %}
                    {% if request.GET.enddate != "" and request.GET.enddate != None %}
                        <p>End Date:{{ request.GET.enddate }}</p>
                    {% endif %}
                    {% if all_orders %}
                        <table class="table table-striped">
                            <thead>
                              <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th>Number</th>
                                <th>Date</th>
                                <th>Time</th>
                                <th>Image</th>
                                <th>Status</th>
                              </tr>
                            </thead>
                            <tbody>
                                {% for orders in all_orders %}
                                    <tr>
                                        <td>{{ orders.id }}</td>
                                        <td>{{ orders.fullname }}</td>
                                        <td>{{ orders.contactnumber }}</td>
                                        <td>{{ orders.date }}</td>
                                        <td>{{ orders.time }}</td>
                                        <td>    <img height="60" width="60" src="{{orders.image1.url}}"></td>
                                        <td> {{ orders.get_status_display }} <br/><a href="{% url 'orderform:updateorder' orders.id %}">Update</a>
                                            <button type="button" class="btn btn-info btn-lg xyz" data-toggle="modal" data-id="{{ orders.id }}" data-target="#myModal" >Update Status</button>
                                        </td>

                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        {% else %}
                            <p>No Orders</p>
                    {% endif  %}
            </div>
        </div>
{#        <div class ="col-md-1">#}
{#        </div>#}

    </div>
</div>
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Modal Header</h4>
      </div>
      <div class="modal-body">
{#            <form>#}
{#                <div class="form-group">#}
{#                    <input type="hidden" class="form-control" name="orderid" id="orderid" value=""  required="true">#}
{#                </div>#}
{#                <div class="form-group">#}
{#                    <label for="sel1">Cake Flavour:</label>#}
{#                    <select class="form-control" id="sel1">#}
{#                        <option>Chocolate Fudge</option>#}
{#                        <option>Plain Cheese</option>#}
{#                        <option>Chocolate Chip</option>#}
{#                        <option>Nutella</option>#}
{#                    </select>#}
{#                </div>#}
{#                <button type="submit" class="btn btn-default">Update Order Status</button>#}
{#            </form>#}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>
{% endblock %}

orderform/templates/orderform/order_form.html
{% extends 'orderform/cakemonster.html' %}

{% block title%}
CakeMonster Order Form
{% endblock%}

{% block head %}
<style>
.form-control
{
margin:0px !important;
height:30px !important;
line-height:10px !important;
}

.margin-to-align
{
margin-left: 22px;
}
</style>
<script>
function checkdate() {
   var selectedText = document.getElementById('id_date').value;
   var selectedDate = new Date(selectedText);
   var now = new Date();
   console.log(selectedDate);
   console.log(now);
   console.log(now.getUTCDate());
   console.log(now.getUTCMonth());
   console.log(selectedDate.getUTCDate());
   console.log(selectedDate.getUTCMonth());

   if (selectedDate.getUTCFullYear() < now.getUTCFullYear() ||
       (selectedDate.getUTCMonth() < now.getUTCMonth() && selectedDate.getUTCFullYear() == now.getUTCFullYear())||
       ((selectedDate.getUTCDate() < now.getUTCDate()) && (selectedDate.getUTCMonth() == now.getUTCMonth()))
   )
   {
    alert("Delivery Date must be in future");
    document.getElementById('id_date').value = "";
   }
 }
</script>

{% endblock %}

{% block body%}
<div class="container">
    {% if request.GET.posted == 'yes' %}
        <div class="row">
            <div class ="col-md-3">
            </div>
            <div class ="col-md-6 alert alert-success margin-to-align">
                Order Posted Successfully.
            </div>
            <div class ="col-md-3">
            </div>
        </div>
    {% endif %}
    <div class="row">
        <div class ="col-md-3">
        </div>
        <div class ="col-md-6 well margin-to-align" >
            <form   id="orderform" action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                    <!--<div class="form-group">-->
                        {% if field.errors %}
                        <div class="alert alert-danger"> {{ field.errors }} </div>
                        {% endif %}
                        <label class="control-label" style="text-align:left">{{ field.label }}</label>
                        {{ field }}
                    <!--</div>-->
                 {% endfor %}
                 <div class="col-md-4"></div>
                 <div class="col-md-4">
                      <button type="submit" class="btn btn-default">Place Order</button>
                 </div>
                 <div class="col-md-4"></div>
            </form>
        </div>
        <div class ="col-md-3">
        </div>
    </div>
</div>
{% endblock %}

orderform/templates/orderform/orders.html
{#{% extends 'orderform/base.html' %}#}
{% extends 'orderform/cakemonster.html' %}

{% block title%}
CakeMonster Order List
{% endblock%}

{% block head %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
<style>
.btn {
padding: 5px 5px !important;
border-radius: 5px !important;
text-transform: initial !important;
width: 168px !important;
font-size: 12px !important;
}

.searchbydate
{
text-align: center
}

.showallorders
{
text-align: center;
margin-top: 12px;
}


img
{
border-radius: 30px !important;

}
</style>
<script>
function search_by_date() {
    var startdate = document.getElementById('startdate').value;
    var enddate = document.getElementById('enddate').value;
    var url_mask = "{% url 'orderform:listorders' %}";
    url_mask = url_mask + "?startdate=" + startdate + "&enddate=" + enddate;

    return url_mask;
    window.open(url_mask);
}

function search_tomorrow() {
    var current_date = new Date();
    var month = current_date.getMonth() + 1;
    var day = current_date.getDate() + 1;
    var year = current_date.getFullYear();

    var formatted_date_string = year + '-' + month + '-' + day ;

    console.log(formatted_date_string);

    var url_mask = "{% url 'orderform:listorders' %}";
    url_mask = url_mask + "?startdate=" + formatted_date_string + "&enddate=" + formatted_date_string;

    return url_mask;
}
function search_today() {
    var current_date = new Date();
    var month = current_date.getMonth() + 1;
    var day = current_date.getDate();
    var year = current_date.getFullYear();

    var formatted_date_string = year + '-' + month + '-' + day ;

    console.log(formatted_date_string);

    var url_mask = "{% url 'orderform:listorders' %}";
    url_mask = url_mask + "?startdate=" + formatted_date_string + "&enddate=" + formatted_date_string;

    return url_mask;
}

</script>
<script>

$(document).ready( function () {
    $('.table').DataTable({
    "order": [],
  "columnDefs": [
    { className: "dt-center", "targets": [ 0,1,2,3,4,5,6 ] }
                ]
    });
} );

$(document).on("click", ".xyz", function () {
     var myBookId = $(this).data('id');
        console.log("working?");
        console.log(myBookId);
        var url_mask = "{% url 'orderform:statusupdate' 12345 %}".replace(/12345/, myBookId);
 {#$(".modal-body #bookId").val( myBookId );#}
     // As pointed out in comments,
     // it is superfluous to have to manually call the modal.
        $.ajax({url: url_mask, success: function(result){
            console.log(result);
            $(".modal-body").html(result);

            $('#orderform').attr('action', url_mask);

        }});
      {#$('.modal-body .form-group #orderid').val(myBookId);#}
});

</script>
{% endblock %}

{% block body%}
<div class="container">
    <div class="row form-inline showallorders" >
        <!--<div class ="col-md-12">-->
            <!--<div class ="form-group searchbydate" >-->
                <!--<form class="form-inline" action="" method="GET" >-->
                    <div class="col-md-3">
                    </div>
                    <div class="col-md-3" >
                      <label for="date">Start Date:</label>
                      <input type="date" class="input-sm" placeholder="Enter start date" id="startdate" name="startdate">
                      <!--<input type="date" placeholder="Enter start date" id="startdate" name="startdate">-->
                    </div>
                    <div class="col-md-3">
                      <label for="date">&nbsp  End Date:</label>
                      <input type="date" class="input-sm" placeholder="Enter end date" name="enddate" id="enddate">
                      <!--<input type="date" placeholder="Enter end date" name="enddate" id="enddate">-->
                    </div>
                    <div class="col-md-3">
                    </div>
                    <!--<button type="submit" class="btn btn-default">Search</button>-->
                <!--</form>-->
            <!--</div>-->
            <!--<div class ="col-md-3 showallorders">-->
                <!--&lt;!&ndash;<button class="btn btn-info btn-lg" onclick="window.location.href='{% url 'orderform:listorders' %}'">Show All Orders</button>&ndash;&gt;-->
                <!--&lt;!&ndash;<form action="{% url 'orderform:listorders'  %}" method="GET" >&ndash;&gt;-->
                    <!--&lt;!&ndash;<button type="submit" class="btn btn-default">Show All Orders</button>&ndash;&gt;-->
                <!--&lt;!&ndash;</form>&ndash;&gt;-->
            <!--</div>-->
        <!--</div>-->
    </div>
    <div class="row searchbydate showallorders" >
        <div class="col-md-12">
                <!--<button class="btn btn-info btn-lg" onclick="window.location.href='{% url 'orderform:listorders' %}'">Search By Date</button>-->
                <!--<button class="btn btn-info btn-lg" onclick="search_by_date();">Search By Date</button>-->
                <button class="btn btn-info btn-lg" onclick="window.location.href=search_by_date();">Search By Date</button>
        </div>
    </div>
    <div class="row searchbydate showallorders" >
        <div class="col-md-12">
                <button class="btn btn-info btn-lg" onclick="window.location.href=search_today();" >Show Orders For Today</button>
                <button class="btn btn-info btn-lg" onclick="window.location.href=search_tomorrow();">Show Order For Tomorrow</button>
                <button class="btn btn-info btn-lg" onclick="window.location.href='{% url 'orderform:listorders' %}'">Show All Orders</button>
        </div>
    </div>
    <div class="row">
{#        <div class ="col-md-1">#}
{#        </div>#}
        <div class ="col-md-12" >
            <div class="table-responsive">
                <h3 style="text-align:center">Order List</h3>
                        <!--{% if request.GET.startdate != "" and request.GET.startdate != None %}-->
                            <!--<p>Start date: {{ request.GET.startdate }}</p>-->
                        <!--{% endif %}-->
                        <!--{% if request.GET.enddate != "" and request.GET.enddate != None %}-->
                            <!--<p>End Date:{{ request.GET.enddate }}</p>-->
                        <!--{% endif %}-->
                    {% if all_orders %}
                        <table class="table table-striped" >
                            <thead>
                              <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th>Number</th>
                                <th>Date</th>
                                <th>Time</th>
                                <th>Image</th>
                                <th>Status</th>
                              </tr>
                            </thead>
                            <tbody>
                                {% for orders in all_orders %}
                                    <tr>
                                        <td>{{ orders.id }}</td>
                                        <td>{{ orders.fullname }}</td>
                                        <td>{{ orders.contactnumber }}</td>
                                        <td>{{ orders.date }}</td>
                                        <td>{{ orders.time }}</td>
                                        <td>    <img height="60" width="60" src="{{orders.image1.url}}"></td>
                                        <td>
                                            {{ orders.get_status_display }} <br/>
                                            <button type="button" class="btn btn-info btn-lg xyz" data-toggle="modal" data-id="{{ orders.id }}" data-target="#myModal" >Update Status</button>
                                            <!--<button class="btn btn-info btn-lg" onclick="window.location.href='{% url 'orderform:updateorder' orders.id %}'">Edit Order</button>-->
                                            <!--<a href="{% url 'orderform:updateorder' orders.id %}" title="Edit Order"><i class="material-icons">&#xe22b;</i></a>-->
                                        </td>

                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        {% else %}
                            <p>No Orders</p>
                    {% endif  %}
            </div>
        </div>
{#        <div class ="col-md-1">#}
{#        </div>#}

    </div>
</div>
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title" style="text-align:center;">Update Status</h4>
      </div>
      <div class="modal-body" style="text-align:center">
{#            <form>#}
{#                <div class="form-group">#}
{#                    <input type="hidden" class="form-control" name="orderid" id="orderid" value=""  required="true">#}
{#                </div>#}
{#                <div class="form-group">#}
{#                    <label for="sel1">Cake Flavour:</label>#}
{#                    <select class="form-control" id="sel1">#}
{#                        <option>Chocolate Fudge</option>#}
{#                        <option>Plain Cheese</option>#}
{#                        <option>Chocolate Chip</option>#}
{#                        <option>Nutella</option>#}
{#                    </select>#}
{#                </div>#}
{#                <button type="submit" class="btn btn-default">Update Order Status</button>#}
{#            </form>#}
      </div>
      <div class="modal-footer">
        <!--<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>-->
      </div>
    </div>

  </div>
</div>
{% endblock %}

orderform/templates/orderform/statusupdate_form.html
<form   id="orderform" action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
        <div class="form-group">
            {{ field.errors }}
            <label class="control-label" style="text-align:center">{{ field.label_tag }}</label>
                {{ field }}
        </div>
     {% endfor %}
     <div class="col-md-4"></div>
     <div class="col-md-4">
          <button type="submit" class="btn btn-default">Update Status</button>
     </div>
     <div class="col-md-4"></div>
</form>

templates/orderform.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
    <div class="row">
        <div class ="col-md-4">
        </div>
        <div class ="col-md-4">
            <h1> Order Form</h1>
            <form>
                <div class="form-group">
                    <label>Full Name:</label>
                    <input type="text" class="form-control" name="fullname" required="true">
                </div>
                <div class="form-group">
                    <label>Contact Number:</label>
                    <input type="number" class="form-control" name="number" required="true>
                </div>
                <div class="form-group">
                    <label>Delivery Date:</label>
                    <input type="date" class="form-control" name="date" required="true>
                    </div>
                <div class="form-group">
                    <label>Delivery time:</label>
                    <input type="time" class="form-control" name="time" required="true>
                    <span class="help-block">Please set time atleast 2 hours before your event.</span>
                </div>
                <div class="form-group">
                    <label for="sel1">Cake Flavour:</label>
                    <select class="form-control" id="sel1">
                        <option>Chocolate Fudge</option>
                        <option>Plain Cheese</option>
                        <option>Chocolate Chip</option>
                        <option>Nutella</option>
                    </select>
                </div>
                <div class="form-group">
                    <label>Cake Image 1:</label>
                    <input type="file" class="form-control" name="image1" required="true">
                </div>
                <div class="form-group">
                    <label>Cake Image 2:</label>
                    <input type="file" class="form-control" name="image2">
                </div>
                <button type="submit" class="btn btn-default">Place Order</button>
            </form>
        </div>
        <div class ="col-md-4"></div>
    </div>
</div>

</body>
</html>

templates/signin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>signin</title>
</head>
<body>
{% if message %}
    <p> Invalid Credentials </p>
{% endif %}
<form action="postsignin" method="post">
    {% csrf_token %}
    Email:
    <input type="email" name="email">
    Password :
    <input type="password" name="pass">
    <input type="submit" value="signin">
</form>

</body>
</html>

templates/welcome.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
welcome {{e}}
</body>
</html>